name: news_app
description: "News App with Api"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0-42.2.beta <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # all needed dependency
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  timeago: ^3.6.0
  webview_flutter: ^4.4.2
  # For integrating firebase
  firebase_core: ^2.24.2
  # For handling firebase authentication
  firebase_auth: ^4.1.3
  # For accessing cloud firestore database
  cloud_firestore: ^4.1.0
  flutter_local_notifications: ^13.0.0
  firebase_database: ^10.4.0
  provider: ^6.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
     - assets/images/
